name: Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Build and Commit
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "."
        pre-build-command: "pip install sphinxcontrib-plantuml sphinx_rtd_theme && make clean"
        build-command: "make html"
    - uses: actions/upload-artifact@v1
      with:
        name: Documentation
        path: _build/html/
    - name: Commit documentations to gh-pages
      run: |
        git clone https://github.com/jayaregalinada/flexisourceit-recruitment-docs.git --branch gh-pages --single-branch gh-pages
        cp -r _build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git add .
        git commit -m "Updated documentation" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.ACCESS_TOKEN }}